name: Build Aurora Inference Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "inference/**"
      - ".github/workflows/build-inference.yml"

env:
  IMAGE_NAME: aayud/aurora-inference

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "tag=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
            -t $IMAGE_NAME:${{ steps.vars.outputs.tag }} \
            -t $IMAGE_NAME:latest \
            inference/runtime

      - name: Push image
        run: |
          docker push $IMAGE_NAME:${{ steps.vars.outputs.tag }}
          docker push $IMAGE_NAME:latest
